name: Commit Discussion on GitHub

on:
  push:
    branches:
      - main # Triggers when a commit is pushed to the 'main' branch.

jobs:
  create-discussion:
    name: Create GitHub Discussion
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Get Commit Details
        run: |
          echo "Fetching commit details..."
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_HASH=$(git log -1 --pretty=format:"%H")
          AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
          AUTHOR_GITHUB=$(git log -1 --pretty=format:"%ae")
    
          echo "Commit Message: $COMMIT_MESSAGE"
          echo "Commit Hash: $COMMIT_HASH"
          echo "Author: $AUTHOR_NAME <$AUTHOR_GITHUB>"
    
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_ENV
          echo "AUTHOR_GITHUB=$AUTHOR_GITHUB" >> $GITHUB_ENV
    
      - name: Get GitHub Discussion Category ID
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: jay86050
          REPO_NAME: mygit_action
        run: |
          echo "Fetching Discussion Category ID..."
          CATEGORY_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/discussions/categories \
            | jq '.[] | select(.name == "General") | .id')
    
          echo "CATEGORY_ID=$CATEGORY_ID" >> $GITHUB_ENV
    
      - name: Create Discussion in GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: jay86050
          REPO_NAME: mygit_action
        run: |
          echo "Creating discussion in GitHub..."
          DISCUSSION_PAYLOAD=$(jq -n \
            --arg title "New Commit: $COMMIT_MESSAGE" \
            --arg body "*Commit Details:*\n\n- **Commit Hash:** $COMMIT_HASH\n- **Author:** $AUTHOR_NAME (<$AUTHOR_GITHUB>)\n- **Commit Message:** $COMMIT_MESSAGE" \
            --argjson category_id "$CATEGORY_ID" \
            '{title: $title, body: $body, category_id: $category_id}')
    
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$DISCUSSION_PAYLOAD" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/discussions
