name: Commit Discussion on GitHub

on:
  push:
    branches:
      - main # Triggers when a commit is pushed to the 'main' branch.

jobs:
  create-discussion:
    name: Create GitHub Discussion
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Get Commit Details
        run: |
          echo "Fetching commit details..."
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_HASH=$(git log -1 --pretty=format:"%H")
          AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
          AUTHOR_GITHUB=$(git log -1 --pretty=format:"%ae")
    
          echo "Commit Message: $COMMIT_MESSAGE"
          echo "Commit Hash: $COMMIT_HASH"
          echo "Author: $AUTHOR_NAME <$AUTHOR_GITHUB>"
    
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_ENV
          echo "AUTHOR_GITHUB=$AUTHOR_GITHUB" >> $GITHUB_ENV

      - name: Get Repository ID
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: jay86050
          REPO_NAME: mygit_action
        run: |
          echo "Fetching repository ID..."
          
          REPO_ID=$(curl -s -X POST -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v4+json" \
            -H "Content-Type: application/json" \
            --data '{"query": "query { repository(owner: \"'$REPO_OWNER'\", name: \"'$REPO_NAME'\") { id } }"}' \
            https://api.github.com/graphql | jq -r '.data.repository.id')

          if [ -z "$REPO_ID" ] || [ "$REPO_ID" == "null" ]; then
            echo "Error: Could not retrieve repository ID."
            exit 1
          fi

          echo "Repository ID: $REPO_ID"
          echo "REPO_ID=$REPO_ID" >> $GITHUB_ENV

      - name: Get Category ID
        run: |
          echo "Category ID: $CATEGORY_ID" # Ensure CATEGORY_ID is being passed correctly
          
      - name: Create Discussion in GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ID: ${{ env.REPO_ID }}
          CATEGORY_ID: "43701223"  # Ensure this is a valid category ID
        run: |
          echo "Creating discussion in GitHub..."

          echo "Commit Message: $COMMIT_MESSAGE"
          echo "Repository ID: $REPO_ID"
          echo "Category ID: $CATEGORY_ID"

          GRAPHQL_QUERY=$(jq -n \
            --arg repoId "$REPO_ID" \
            --arg categoryId "$CATEGORY_ID" \
            --arg title "New Commit: $COMMIT_MESSAGE" \
            --arg body "*Commit Details:*\n\n- **Commit Hash:** $COMMIT_HASH\n- **Author:** $AUTHOR_NAME (<$AUTHOR_GITHUB>)\n- **Commit Message:** $COMMIT_MESSAGE" \
            '{ "query": "mutation createDiscussion($repoId: ID!, $categoryId: ID!, $title: String!, $body: String!) { createDiscussion(input: {repositoryId: $repoId, categoryId: $categoryId, title: $title, body: $body}) { discussion { id } } }" }')

          echo "GraphQL Query: $GRAPHQL_QUERY"  # Debugging the query

          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v4+json" \
            -H "Content-Type: application/json" \
            -d "$GRAPHQL_QUERY" \
            https://api.github.com/graphql
