name: Commit Log and Tagging Author

on:
  push:
    branches:
      - main  # Trigger on push to the 'rutick' branch.

jobs:
  generate-log-and-tag-author:
    name: Generate Commit Log and Tag Author
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Commit Description and Log
        run: |
          echo "Generating commit description and log..."
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')  # Get the author of the commit.
          AUTHOR_GITHUB=$(git log -1 --pretty=format:'%ae')  # Get the author's GitHub email.

          echo "Commit Message: $COMMIT_MESSAGE"
          echo "Commit by: $AUTHOR_NAME <$AUTHOR_GITHUB>" > commit-log.txt
          echo "Commit Description: $COMMIT_MESSAGE" >> commit-log.txt
          cat commit-log.txt

      - name: Upload Commit Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-log
          path: commit-log.txt

      - name: Create GitHub Discussion
        run: |
          echo "Creating a discussion in the General category..."
          curl -X POST \
            -H "Authorization: token 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" \
            -H "Content-Type: application/json" \
            -d '{
                  "title": "Commit Log: '$COMMIT_MESSAGE'",
                  "body": "This commit was made by @'$AUTHOR_NAME'.\n\n**Commit Message:**\n'$COMMIT_MESSAGE'\n\n**Commit Log:**\n'$COMMIT_MESSAGE'\n\n**Author:** @'$AUTHOR_NAME'.",
                  "category": "general"
                }' \
            https://api.github.com/repos/jay86050/mygit_action/discussions
